version: '3.7'
services:
  flexget:
    image: xingsu1021/pthelper:latest
    container_name: pthelper
    restart: always
    volumes:
      - 本地目录/db:/db
      - 本地目录/logs:/logs
      - 本地目录/backups:/backups
      - 本地目录/conf:/conf
    ports:
      - "本地端口:80"
